// ==================== 心安所寄 - 完整数据库 ====================
// 包含17位神明的详细信息和签文数据

const DATABASE = {
    // ==================== 分类数据 ====================
    categories: [
        {
            id: "fertility",
            name: "生育与家庭",
            icon: "👶",
            color: "#E8B4B8",
            gradient: "#F5E6E8",
            description: "求子保胎,家庭和睦",
            fullDescription: "新生命的到来,是家庭最大的喜悦。诚心祈愿,祈求神明赐福,愿母子平安,家庭美满。",
            deities: ["guanyin_songzi", "qixiannv", "taishen"]
        },
        {
            id: "love",
            name: "姻缘与情感",
            icon: "💕",
            color: "#F4C2C2",
            gradient: "#FFF0F0",
            description: "良缘佳偶,情感顺遂",
            fullDescription: "好的姻缘值得等待,好的感情需要经营。祈求月老牵线,愿有情人终成眷属,愿相爱之人白头偕老。",
            deities: ["yuexialao", "hehe_erxian", "nvwa"]
        },
        {
            id: "career",
            name: "学业与事业",
            icon: "📚",
            color: "#B8D4E8",
            gradient: "#E8F4F8",
            description: "金榜题名,事业有成",
            fullDescription: "十年寒窗,一朝题名;职场奋斗,步步高升。祈求文昌护佑,愿你学业精进,事业顺遂。",
            deities: ["wenchang", "guansheng", "kuixing"]
        },
        {
            id: "wealth",
            name: "财富与商业",
            icon: "💰",
            color: "#F4E4C1",
            gradient: "#FFF9E6",
            description: "财源广进,生意兴隆",
            fullDescription: "君子爱财,取之有道。祈求财神相助,愿你正财稳固,偏财有门,生意兴隆,财源广进。",
            deities: ["bigan", "zhaogongming", "guangong_wealth"]
        },
        {
            id: "health",
            name: "健康与长寿",
            icon: "🌿",
            color: "#C8E6C9",
            gradient: "#E8F5E9",
            description: "身体康健,福寿绵长",
            fullDescription: "身体是革命的本钱,健康是最大的财富。祈求药师佛加持,愿你身体健康,疾病远离,福寿安康。",
            deities: ["yaoshi", "nanji", "baosheng"]
        },
        {
            id: "safety",
            name: "出行与平安",
            icon: "🧭",
            color: "#D1C4E9",
            gradient: "#F3F0FF",
            description: "出入平安,一路顺风",
            fullDescription: "出门在外,平安第一。祈求妈祖、哪吒护佑,愿你行程顺利,一路平安,早日归来。",
            deities: ["mazu", "nezha", "tudi"]
        }
    ],

    // ==================== 神明数据 ====================
    deities: {
        // 生育与家庭 (3位)
        guanyin_songzi: {
            id: "guanyin_songzi",
            name: "送子观音",
            category: "fertility",
            image: "神仙图片/送子观音.png",
            avatar: "神仙图片/送子观音.png",
            title: "大慈大悲观世音菩萨",
            description: "大慈大悲,救苦救难,赐子送福",
            background: "观音菩萨,梵文Avalokiteśvara,又译观世音、观自在、光世音。在佛教中,她是西方极乐世界阿弥陀佛座下的上首菩萨,与大势至菩萨并称\"西方三圣\"。送子观音作为观音菩萨三十三化身之一,是中国民间信仰中最为亲民的形象。传说她心怀大悲,巡行世间,闻声救苦。凡求子者,只要志诚礼拜,称念其名号,即可得感应,获赐麟儿。其背后往往配以竹林、莲台、祥云,象征清净与慈悲。",
            detailedIntro: "送子观音起源于晋唐时期,流行于宋明。在民间传说中,她曾多次化身为人,救度难产母亲,保佑幼童平安。在艺术形象上,她常怀抱男童,端坐于白莲之上,神态安详庄严。其愿力广大,不仅保佑求子,更护佑家庭美满,不仅是宗教神祇,更是华夏文明中母爱与慈悲的象征。",
            scenarios: ["备孕求子", "保胎安胎", "祈求母子平安"],
            bgColor: "#F5E6E8",
            textColor: "#8B4789",
            sutraName: "观音心咒",
            musicName: "大辞大悲",
            musicUrl: "https://www.chosic.com/wp-content/uploads/2021/07/The-Zen-Way.mp3",
            sutraUrl: "https://www.chosic.com/wp-content/uploads/2021/07/Rain-and-Thunder.mp3",
            voiceMessage: "慈悲为怀，愿力所及，必有所应；诚心祈愿，麟儿自到。"
        },
        qixiannv: {
            id: "qixiannv",
            name: "七仙女",
            category: "fertility",
            image: "神仙图片/七仙女(王母娘娘之女).png",
            avatar: "神仙图片/七仙女(王母娘娘之女).png",
            title: "王母娘娘之女",
            description: "天上仙女,主管生育,赐福人间",
            background: "七仙女,民间传说中玉皇大帝与王母娘娘的七个女儿。她们不仅代表着天上的纯洁与美好,在民间信仰中更被赋予了掌管人间女红、生育及女性命运的神性。其中最小的七妹与董永的爱情故事家喻户晓,使七仙女成为慈怜人间、勇于追求幸福的象征。在求子习俗中,七仙女因其女性特质,常被视为保佑女童健康成长及赐予聪明伶俐女儿的重要神祇。",
            detailedIntro: "七仙女的信仰深深扎根于农耕文化,她们常与织锦、云霞相关联。在华南及东南亚华人社区,七仙女也被称为\"七娘妈\",是孩童的守护神。每逢七夕,家长会带孩子祭拜,祈求神灵保佑孩子无灾无难。在求子祈愿中,七仙女因其温柔慈悲的性格,常带给求子家庭祥瑞之气,是家庭幸福的守护仙子。",
            scenarios: ["求女", "求双胞胎", "祈求女儿健康"],
            bgColor: "#FFF0F5",
            textColor: "#DB7093",
            sutraName: "七仙祈福咒",
            musicName: "仙乐飘飘",
            musicUrl: "assets/audio/bgm/qixiannv.mp3",
            sutraUrl: "assets/audio/sutra/qixian_chant.mp3",
            voiceMessage: "仙凡有情，愿你家庭和睦，子女聪慧，共享天伦。"
        },
        taishen: {
            id: "taishen",
            name: "胎神",
            category: "fertility",
            image: "神仙图片/胎神.png",
            avatar: "神仙图片/胎神.png",
            title: "护胎保产之神",
            description: "专司保胎,护佑母子,平安顺产",
            background: "胎神,民间信仰中专门护佑孕妇及胎儿的神灵。古人认为从受孕那一刻起,胎神便降临家中,随着孕期月份的推移,依次在床、房门、厨房等不同位置\"驻守\"。胎神的职能非常具体——保护胎儿在母体中安定成长,防止外邪侵扰。因此,孕期有许多关于\"避胎神\"的禁忌,如不可随意搬动床铺、动土钉钉等,皆是为了不惊扰这位忠实的守护神。",
            detailedIntro: "胎神信仰体现了古代中医养生观与民间禁忌的结合,核心目标是为孕妇创造一个绝对宁静、环境变化最小的生养空间。在现代语境下,祈愿胎神实则是寻求一份心理上的安定与祥瑞。无论是在备孕期还是怀孕期,诚心祈愿胎神守护,旨在祈求神灵保佑胎位端正、生产顺利,让每一位新生命都能平安降临人间。",
            scenarios: ["保胎", "孕期平安", "顺产祈愿"],
            bgColor: "#FFF8DC",
            textColor: "#CD853F",
            sutraName: "保胎平安咒",
            musicName: "安胎曲",
            musicUrl: "assets/audio/bgm/taishen.mp3",
            sutraUrl: "assets/audio/sutra/taishen_ritual.mp3",
            voiceMessage: "吾在此守护，愿母子连心，胎元稳固，平安顺产。"
        },

        // 姻缘与情感 (3位)
        yuexialao: {
            id: "yuexialao",
            name: "月下老人",
            category: "love",
            image: "神仙图片/月下老人.png",
            avatar: "神仙图片/月下老人.png",
            title: "主管姻缘之神",
            description: "主管天下姻缘,以红绳系足,牵线有情人",
            background: "月下老人,简称月老,是中国民间信仰中主管男女婚姻之神。其形象最早见于唐人小说《续玄怪录》。描写他白须飘飘,左手持《姻缘簿》,右手牵红绳,常趁月色翻阅书册查寻天下有情人的姻缘轨迹。正如古诗云:\"千里姻缘一线牵\",月老手中简单的红绳,却能跨越万水千山与时空阻碍,将命中注定的两人紧紧相系。在婚嫁文化中,月老象征着缘分的奇妙与不可抗拒。",
            detailedIntro: "月老信仰反映了华夏文明对\"缘\"的追求。无论身处何地,人们总相信冥冥之中有月老在主持公道。月老庙中常挂满写有名字的红绳,象征信众对真爱的渴望。祈愿月老,不仅是求取一段感情的开始,更是求取两人性格的磨合与终身的守望。它是对\"愿得一人心,白首不相离\"这种美好愿景最直接的表达。",
            scenarios: ["单身求缘", "挽回感情", "祈求婚姻幸福"],
            bgColor: "#FFE4E1",
            textColor: "#DC143C",
            sutraName: "姻缘祈福咒",
            musicName: "月下仙音",
            musicUrl: "https://www.chosic.com/wp-content/uploads/2021/04/And-So-It-Begins-Inspired-By-Crush-Sometimes.mp3",
            sutraUrl: "https://www.chosic.com/wp-content/uploads/2021/04/And-So-It-Begins-Inspired-By-Crush-Sometimes.mp3",
            voiceMessage: "姻缘天定，红绳系足。珍惜当下，自会良缘佳偶。"
        },
        hehe_erxian: {
            id: "hehe_erxian",
            name: "和合二仙",
            category: "love",
            image: "神仙图片/和合二仙.png",
            avatar: "神仙图片/和合二仙.png",
            title: "和睦美满之神",
            description: "主管和合,促进夫妻和睦,家庭美满",
            background: "和合二仙,即唐代僧人寒山与拾得。在民间传说中,他们一人持荷(和),一人捧盒(合),形象诙谐喜庆,常被称为\"和圣\"与\"合圣\"。清朝雍正帝封其为\"和合二圣\",由此正式定型为掌管婚姻和睦、家庭圆满、万事如意的喜神。如果你感到家庭琐事繁多或夫妻间偶有摩擦,和合二仙的信仰能为你带来包容、幽默与化解矛盾的智慧。",
            detailedIntro: "和合文化是中华传统文化中\"家和万事兴\"理念的具象化。寒山与拾得的深厚友谊升华为神圣的和谐力量。人们在婚礼或新婚居室中常张贴二仙贴画,以祈求百年好合。祈愿和合二仙,重在求取内心的平和与对他人的体谅,让家庭成员间能像二仙那样互敬互爱,让琐碎的生活充满欢声笑语。",
            scenarios: ["夫妻和睦", "化解矛盾", "家庭和谐"],
            bgColor: "#FFF0F5",
            textColor: "#FF69B4",
            sutraName: "和合咒",
            musicName: "和合之音",
            musicUrl: "assets/audio/bgm/hehe.mp3",
            sutraUrl: "assets/audio/sutra/hehe_song.mp3",
            voiceMessage: "和气生财，合心致远。愿人间常驻欢笑，夫妻百年好合。"
        },
        nvwa: {
            id: "nvwa",
            name: "女娲娘娘",
            category: "love",
            image: "神仙图片/女娲娘娘.png",
            avatar: "神仙图片/女娲娘娘.png",
            title: "造人补天之神",
            description: "创造人类,主管婚配,赐福姻缘",
            background: "女娲娘娘,华夏民族始祖女神。在神话传说中,她抟土造人,化生万物,更在天崩地裂时炼五色石以补苍天。作为\"神媒\",女娲确立了最初的婚姻婚配制度,被后世尊为\"婚姻之神\"。她不仅是宇宙的修复者,更是人际关系、尤其男女结合的最高架构师。其形象神圣而威严,寄托了先民对生命生生不息、社群稳定传承的热切期盼。",
            detailedIntro: "女娲信仰融合了母系社会的文化遗存与对创造力的绝对崇拜。在求子的分类中,女娲也有极高的地位,因为她是人类灵魂的创造者。在求姻缘方面,向女娲祈愿意味着追求一份更有深度、更符合自然法则的结合。祈愿女娲娘娘,是寻求一种生命能量的庇佑,愿感情如五色石般坚固,如补天之举般宏大而深远。",
            scenarios: ["祈求真爱", "婚姻美满", "子嗣昌盛"],
            bgColor: "#F0E68C",
            textColor: "#DAA520",
            sutraName: "女娲祈福经",
            musicName: "补天遗音",
            musicUrl: "assets/audio/bgm/nvwa.mp3",
            sutraUrl: "assets/audio/sutra/nvwa_prayer.mp3",
            voiceMessage: "补天功成，造化弄人。愿其灵感指引，赐你一生幸福。"
        },

        // 学业与事业 (3位)
        wenchang: {
            id: "wenchang",
            name: "文昌帝君",
            category: "career",
            image: "神仙图片/文昌帝君.png",
            avatar: "神仙图片/文昌帝君.png",
            title: "主掌功名利禄之神",
            description: "主掌功名利禄,司天下文运,佑考生学子",
            background: "文昌帝君,全称\"辅元开化文昌司禄宏仁帝君\",是中国民间和道教尊奉的掌管功名禄位之神。文昌原为星名(文昌六星),后演变为神祇。相传帝君曾七十三化为人身,世为郎守,其心慈悯,致力于开化人间。在文化传统中,文昌帝君不仅保佑考试顺利,更倡导\"阴骘文\",劝导世人广行阴德、戒除贪婪。其形象多为文职官员,手持如意或朱笔,身跨白螺,象征智慧与清正。",
            detailedIntro: "文昌帝君的信仰在元、明两代达到巅峰。无论是古代科举时代的举子,还是现代面临升学的中学生,文昌帝君都是文运的象征。在全国各地的文昌祠中,常有孔子、朱熹等儒家圣贤陪祀,体现了儒道融合的特征。祈愿文昌,既是求取名次,更是求取智慧的开悟与心态的平稳。",
            scenarios: ["考试升学", "求职晋升", "文章著作"],
            bgColor: "#E0F2F7",
            textColor: "#0277BD",
            sutraName: "文昌帝君阴骘文",
            musicName: "文昌正气",
            musicUrl: "https://www.chosic.com/wp-content/uploads/2021/05/Peaceful-Morning.mp3",
            sutraUrl: "https://www.chosic.com/wp-content/uploads/2021/05/Peaceful-Morning.mp3",
            voiceMessage: "文运昌隆，金榜题名。灵台清明，自见广阔乾坤。"
        },
        guansheng: {
            id: "guansheng",
            name: "关圣帝君",
            category: "career",
            image: "神仙图片/关圣帝君.png",
            avatar: "神仙图片/关圣帝君.png",
            title: "忠义仁勇之神",
            description: "主管事业运、职场,护佑忠义之士",
            background: "关圣帝君,即三国名将关羽。在华夏文化中,关羽不仅是武将的顶峰,更被道、释、儒三教共尊,神衔极高。他以\"忠、义、仁、勇\"名动天下,封号从\"候\"升至\"帝\",至圣至尊。在职场与事业领域,关公被奉为守护神,主张诚信、正直与坚毅。事业的成功往往建立在契约精神与团队忠诚之上,因此关圣帝君的庇佑往往能带给人面对困难时的正气与果断。",
            detailedIntro: "关圣帝君信仰在宋元之后极其广泛。在事业分类中,他护佑那些身处激烈竞争、需要决策魄力的人士。财神分类中的关公侧重于守财与信用,而事业分类中的帝君则侧重于平步青云、战无不胜。祈愿关圣帝君,不仅是求取成功,更是求得一份做人的原则与内心的坦荡,愿你在职场征途中,能如关圣般英勇而受人敬仰。",
            scenarios: ["求职跳槽", "职场晋升", "事业发展"],
            bgColor: "#FFEBEE",
            textColor: "#C62828",
            sutraName: "关帝觉世真经",
            musicName: "忠义之歌",
            musicUrl: "assets/audio/bgm/guandicheng.mp3",
            sutraUrl: "assets/audio/sutra/guandi_mantra.mp3",
            voiceMessage: "忠义当头，勇冠三军。愿你职场平坦，事倍功半。"
        },
        kuixing: {
            id: "kuixing",
            name: "魁星",
            category: "career",
            image: "神仙图片/魁星(道教).png",
            avatar: "神仙图片/魁星(道教).png",
            title: "主管文采之神",
            description: "主管文采、创意,助文人才思泉涌",
            background: "魁星,道教信仰中主宰文运的神。魁星原指北斗七星的第一星,亦称北斗的斗首。在画像中,魁星常被刻画成青面獠牙、右手执笔、左手托墨斗、一脚独立、一脚向后踢斗的奇特样貌,取\"魁星点斗,金榜题名\"之意。虽然样貌威严甚至有些凶狠,但他却是天下文人眼中最亲切的指引者。凡是被魁星手中硃笔点中的幸运儿,必然能文思如泉涌,笔下生莲花。",
            detailedIntro: "魁星信仰侧重于个人才华的突显。与文昌帝君主管全局名利不同,魁星更关注文采、灵感与独一无二的创意。对于面临创作瓶颈或创意行业的工作者,魁星是最值得祈愿的神灵。祈愿魁星点斗,是追求一种突破瓶颈的爆发力,愿你在考场或职场中,能展现出最具张力的个人才学,一鸣惊人。",
            scenarios: ["创意灵感", "写作创作", "艺术创作"],
            bgColor: "#E8EAF6",
            textColor: "#3F51B5",
            sutraName: "魁星祈福咒",
            musicName: "文思泉涌",
            musicUrl: "assets/audio/bgm/kuixing.mp3",
            sutraUrl: "assets/audio/sutra/creative_flow.mp3",
            voiceMessage: "魁星点斗，名扬天下。愿你才思泉涌，创意无限。"
        },

        // 财富与商业 (3位)
        bigan: {
            id: "bigan",
            name: "文财神比干",
            category: "wealth",
            image: "神仙图片/文财神比干.png",
            avatar: "神仙图片/文财神比干.png",
            title: "文财神",
            description: "主管正财,护佑诚信经商,财源广进",
            background: "比干,商代帝王文丁之子,纣王的叔父。他在历史上以\"赤胆忠心\"著称,敢于直谏却惨遭心脏之害。因其在世时公正公平,甚至被视为\"无心则无偏\",民间遂尊其为文财神。比干主要主管社会的\"正财\"——即因劳动、经商、服务而获得的合理、合法的收入。他所代表的是一种踏实、诚信、童叟无欺的财富观,是经商者的道德标杆。",
            detailedIntro: "比干信仰强调财源的稳定性与正义性。在财富分类中,他是最受实业家和职场稳定收入者推崇的神灵。其形象通常为头戴宰相帽、身穿官服、神态庄重的老者。祈愿文财神比干,不仅仅是求取财富的数量,更是求得财富的\"心安\"。愿你的事业能因诚信而壮大,愿你的收入能随勤奋而稳步递增。",
            scenarios: ["正财运", "诚信经商", "稳定收入"],
            bgColor: "#FFF9C4",
            textColor: "#F57F17",
            sutraName: "财神宝诰",
            musicName: "招财进宝",
            musicUrl: "assets/audio/bgm/bigan_wealth.mp3",
            sutraUrl: "assets/audio/sutra/caishen_mantra.mp3",
            voiceMessage: "生财有道，富贵有恒。持信者必能广进财源。"
        },
        zhaogongming: {
            id: "zhaogongming",
            name: "武财神赵公明",
            category: "wealth",
            image: "神仙图片/武财神赵公明.png",
            avatar: "神仙图片/武财神赵公明.png",
            title: "武财神",
            description: "主管偏财,招财进宝,生意兴隆",
            background: "赵公明,又称赵公元帅。在道教中,他本是统帅众神的武将,后被封为\"金龙如意正一龙虎玄坛真君\",专门统领\"进宝\"、\"纳珍\"、\"招财\"、\"利市\"四位神灵,成为武财神。赵公元帅神武非凡,跨黑虎、持金鞭,主宰世间一切求财之事,尤其在\"偏财\"(非固定收入、投资、商机)方面有极大权威。他能驱雷役电、呼风唤雨,其威猛不仅能招财,亦能镇宅避邪、护商安市。",
            detailedIntro: "赵公明的信仰充满活力与动感。他是商贾云集、商机万变中的定海神针。对于从事投资、短期项目或在新领域开拓事业的人来说,武财神是信心的来源。祈愿武财神赵公明,求的是一种把握机遇的敏锐与果敢。愿你在激烈的商海竞争中能勇往直前,凭智慧与胆识辟出一条致富捷径,财源广进达三江。",
            scenarios: ["偏财运", "生意兴隆", "投资理财"],
            bgColor: "#FFFDE7",
            textColor: "#F9A825",
            sutraName: "赵公明财神咒",
            musicName: "财神到",
            musicUrl: "assets/audio/bgm/zhaogongming.mp3",
            sutraUrl: "assets/audio/sutra/zhaogongming_ritual.mp3",
            voiceMessage: "招财利市，进宝纳珍。乘时而起，必获丰盈。"
        },
        guangong_wealth: {
            id: "guangong_wealth",
            name: "关公",
            category: "wealth",
            image: "神仙图片/关圣帝君.png",
            avatar: "神仙图片/关圣帝君.png",
            title: "商业守护神",
            description: "主管商业诚信,护佑商人,财运亨通",
            background: "在财富领域,关公被尊为\"义财神\"。这源于商人极度重视的\"忠义\"与\"诚信\"。商海浮沉,最重契约与互信,关公义薄云天的色彩,使其成为商业伙伴间必须效法的楷模。作为守护神,关公不仅保佑财运,更具备\"平账、算账\"的能力(传说会计法即关公所创),因此也主掌着商业纠纷的化解与公平。他的大刀能劈开小人侵扰,护佑正义的交易。",
            detailedIntro: "关公在财富分类中地位独特,他不仅是求财,更是\"护财\"。在南方及商贾聚居地,关公像往往摆在店铺最显眼处。祈愿义财神关公,是追求商业经营的长青与人格的升华。愿你的合作方皆是信守承诺之人,愿你的生意因讲求仗义而广受欢迎。祈愿关公,求得是那份坦坦荡荡、义利双收的豪迈气概。",
            scenarios: ["商业合作", "诚信经营", "生意谈判"],
            bgColor: "#FFF3E0",
            textColor: "#E65100",
            sutraName: "关帝财神经",
            musicName: "义财双全",
            musicUrl: "assets/audio/bgm/guangong_caishen.mp3",
            sutraUrl: "assets/audio/sutra/guandi_wealth_chant.mp3",
            voiceMessage: "大义秉然，利财双收。经商之道，信义为先。"
        },

        // 健康与长寿 (3位)
        yaoshi: {
            id: "yaoshi",
            name: "药师佛",
            category: "health",
            image: "神仙图片/药师佛.png",
            avatar: "神仙图片/药师佛.png",
            title: "东方琉璃世界教主",
            description: "主管医药,消灾延寿,身体康健",
            background: "药师琉璃光如来,简称药师佛。在佛学中,他是东方净琉璃世界的教主。此神灵不仅具备无上的佛法智慧,更立下十二大愿,立志解除众生身体上的疾病与心灵上的贪嗔痴之苦。其左手持药钵(或塔),右手作施无畏印,周身散发出清冷的蓝色琉璃光芒,象征清净无染。在信众心中,药师佛是绝望境地中的大医王,是生命力与自愈能力的最终感召。",
            detailedIntro: "药师佛信仰的核心在于\"内外明澈\"。当一个人身体受损时,往往伴随着内心的焦虑。祈愿药师佛,能平息对疾病的恐惧,唤起身体内在的生机。对于大病初愈、身患顽疾或经常感到疲惫的人来说,药师咒的频率能带给人一种清凉的安慰感。祈愿药师如来,求得的是一种全方位的身心平衡,愿琉璃之光普照,让病痛消弭,让寿命绵长。",
            scenarios: ["疾病康复", "身体健康", "消灾延寿"],
            bgColor: "#E1F5FE",
            textColor: "#0277BD",
            sutraName: "药师琉璃光如来本愿功德经",
            musicName: "药师心咒",
            musicUrl: "assets/audio/bgm/yaoshi_buddha.mp3",
            sutraUrl: "assets/audio/sutra/yaoshi_mantra.mp3",
            voiceMessage: "琉璃光照，百病消弥。愿尔离苦得乐，康健如初。"
        },
        nanji: {
            id: "nanji",
            name: "南极仙翁",
            category: "health",
            image: "神仙图片/南极仙翁.png",
            avatar: "神仙图片/南极仙翁.png",
            title: "长寿之神",
            description: "主管长寿,福寿安康,延年益寿",
            background: "南极仙翁,又称长生大帝、寿星。他是道教神话中主管人类寿命的神祇。其外貌特征极具辨识度——高耸而硕大的额头象征着智慧与长寿、随风飘逸的长须、笑容可掬的面容、左手持龙头拐杖,右手常托一枚长寿仙桃。身旁往往跟随着灵鹿与仙鹤。南极仙翁不仅是时间的长者,更是吉祥与松鹤齐龄的化身。其信仰不仅存在于庙宇,更深刻渗透在普通人的日常生活与祝寿文化中。",
            detailedIntro: "南极仙翁的慈祥能够极大地抚慰老人的心理压力。在健康分类中,他不仅代表不生病,更代表一种高质量的、福寿双全的生命状态。如果家中老人近期身体违和,或想为其祈求平安健康,仙翁是最合适的祈愿对象。祈愿南极仙翁,求的是一种晚年生活的安闲与身体机能的稳固,愿福如东海水长流,愿寿比南山不老松。",
            scenarios: ["长寿祈愿", "老人健康", "福寿双全"],
            bgColor: "#F3E5F5",
            textColor: "#7B1FA2",
            sutraName: "南极长生经",
            musicName: "寿比南山",
            musicUrl: "assets/audio/bgm/nanjixianweng.mp3",
            sutraUrl: "assets/audio/sutra/longevity_chant.mp3",
            voiceMessage: "松龄鹤算，福寿双全。静养身心，自得南山之寿。"
        },
        baosheng: {
            id: "baosheng",
            name: "保生大帝",
            category: "health",
            image: "神仙图片/保生大帝.png",
            avatar: "神仙图片/保生大帝.png",
            title: "医神",
            description: "主管医药,治病救人,妙手回春",
            background: "保生大帝,真实历史人物为北宋名医吴夲。相传他在世时医术精湛至极,曾\"点龙眼、医虎喉\",具备跨越物种的慈悲与神效。由于其终生致力于免费为寒门百姓治病,去世后被尊为\"大道公\"、\"医灵真君\"。保生大帝在闽台及东南亚地区影响力极大,他不仅是医术的化身,更是医德的最高典范。在求医问药的关键时刻,保生大帝是病患与家属心中最坚实的依靠。",
            detailedIntro: "保生大帝的信仰更接近人间的温度。他被视为最能理解病患痛苦、最能保佑医疗过程顺利的神。对于面临复杂手术、难以攻克的疑难杂症、或正在积极寻药问医的人们,祈愿保生大帝能给予清醒的头脑与良好的运气。祈愿医圣保生大帝,求得是一份\"药到病除\"的机缘,愿你遇到明医、选对良方,愿身体早日恢复强健。",
            scenarios: ["疾病治疗", "手术平安", "医疗顺利"],
            bgColor: "#E8F5E9",
            textColor: "#2E7D32",
            sutraName: "保生大帝真经",
            musicName: "妙手回春",
            musicUrl: "assets/audio/bgm/baosheng.mp3",
            sutraUrl: "assets/audio/sutra/healing_chant.mp3",
            voiceMessage: "妙手回春，药到病除。愿你早日康复，重焕生机。"
        },

        // 出行与平安 (3位)
        mazu: {
            id: "mazu",
            name: "妈祖",
            category: "safety",
            image: "神仙图片/妈祖.png",
            avatar: "神仙图片/妈祖.png",
            title: "海上守护神",
            description: "主管航海平安,护佑出行,一路顺风",
            background: "妈祖,官名\"天后\",民间尊称林默娘。她是海上和平的化身,起源于宋代福建莆田。林默娘生前识天象、懂医理、救海难,死后羽化登仙,成为所有航海者与水上从业者的最高心理依归。妈祖信仰现已跨越国界,成为全球性的华人民间信仰核心。她象征着一种无私、博大、包容的慈母之爱——无论风浪多大,看到妈祖的火光(导航灯),即是看到了家与岸的希望。",
            detailedIntro: "随着时代发展,妈祖的护佑早已不限于航海,而是延伸到了商务出差、旅游打卡、跨国移民等所有\"行走在路上\"的场景。其形象端庄优美,凤冠霞帔。祈愿妈祖,是寻求一种对未知旅程的全局感应与意外化解。愿你在远行的道路上,能如妈祖林默娘般从容淡定,愿海神之母护卫你的一路坦途,愿你乘风破浪,终能平安归港。",
            scenarios: ["航海出行", "旅行平安", "海外工作"],
            bgColor: "#E0F7FA",
            textColor: "#00838F",
            sutraName: "妈祖平安经",
            musicName: "海天一色",
            musicUrl: "assets/audio/bgm/mazu_ocean.mp3",
            sutraUrl: "assets/audio/sutra/mazu_prayer.mp3",
            voiceMessage: "波平如镜，一路顺风。无论海内天涯，吾自护体。"
        },
        nezha: {
            id: "nezha",
            name: "三太子哪吒",
            category: "safety",
            image: "神仙图片/三太子哪吒.png",
            avatar: "神仙图片/三太子哪吒.png",
            title: "护法天神",
            description: "降妖除魔,护佑平安,驱邪避凶",
            background: "哪吒,道教称\"中坛元帅\",是驱邪斩魔的暴力美学化身。他脚踩风火轮,代表着极速与活力;手持火尖枪,象征着破除一切邪祟的勇气。哪吒在神话中三头六臂,神通广大。他不仅是个性飞扬的小英雄,在平安分类中,他更具备极强的\"清障\"属性——也就是清除前路上的各种小人是非、邪气灾殃。对于那些感到诸事不顺、疑似遭遇不洁能量或小人中伤的人们,哪吒是最具威慑力的护卫者。",
            detailedIntro: "哪吒信仰体现了阳刚与正气的结合。祈愿哪吒,不是被动求安,而是主动制乱。他那敢于挑战权威、斩妖除魔的意志,能带给信众一种破局的力量。无论是在危险的路途中,还是在充满负能量的职场/生活场中,祈愿三太子哪吒,是召唤一份热血与光明。愿你的生活如风火轮般转动生辉,愿一切阴霾在乾坤圈的闪耀下无所遁形。三太子护法,万邪不侵。",
            scenarios: ["驱邪避凶", "出行平安", "化解灾厄"],
            bgColor: "#FCE4EC",
            textColor: "#C2185B",
            sutraName: "哪吒护法咒",
            musicName: "风火轮转",
            musicUrl: "assets/audio/bgm/nezha_vibe.mp3",
            sutraUrl: "assets/audio/sutra/nezha_mantra.mp3",
            voiceMessage: "斩妖除魔，驱邪避厄。正气满乾坤，妖氛自消散。"
        },
        tudi: {
            id: "tudi",
            name: "土地公",
            category: "safety",
            image: "神仙图片/土地公.png",
            avatar: "神仙图片/土地公.png",
            title: "地方守护神",
            description: "主管一方平安,护佑居家,出入平安",
            background: "土地公,又称\"福德正神\"。他是官职最低但离百姓最近的神祇。在古人的观念中,土地载万物,因此也是生财之本、安宁之源。土地公形象常为满面白须、手持元宝或拐杖的长者,神态和蔼得像邻家老人。无论是新房动土、旧宅修缮,还是仅仅想求得片区的邻里和睦,向这位\"地方长官\"祈愿总是最管用的。他是家宅、村落与社区的隐形物业管家,默默注视着每个出口与入口。",
            detailedIntro: "土地公信仰反映了卑谦而务实的幸福观——不求惊天动地,只求脚下的一方土地安宁、出入的小路顺遂。在平安分类中,他主掌防盗、防火及居家安全。对于独居者、经常夜归的人或新搬家的人来说,祈愿土地公能建立起心理上的安全边界。祈愿福德正神,求的是一种最朴素的稳定感。愿土地公公保佑你户牖坚固,愿你出入如常,夜梦吉祥。",
            scenarios: ["居家平安", "搬家入宅", "地方出行"],
            bgColor: "#FFF8E1",
            textColor: "#F57C00",
            sutraName: "土地公福德经",
            musicName: "财源广进",
            musicUrl: "https://www.chosic.com/wp-content/uploads/2021/07/Purify-Your-Mind.mp3",
            sutraUrl: "https://www.chosic.com/wp-content/uploads/2021/07/Purify-Your-Mind.mp3",
            voiceMessage: "平安是福，德在土中。出入顺遂，夜梦吉祥。"
        }
    }
};

// ==================== 导出数据 ====================
if (typeof module !== 'undefined' && module.exports) {
    module.exports = DATABASE;
}
